### ISSUE TITLE
Apply md5 to Native

### ISSUE THREAD

**Issue by ghost** [tiny-express/native#197]
The MD5 algorithm is a widely used hash function producing a 128-bit hash value. Although MD5 was initially designed to be used as a cryptographic hash function, it has been found to suffer from extensive vulnerabilities. It can still be used as a checksum to verify data integrity, but only against unintentional corruption.
Like most hash functions, MD5 is neither encryption nor encoding.

**Comment by tiny-express** [comment]
http://docs.oracle.com/javase/8/docs/api/java/security/MessageDigest.html
