### ISSUE TITLE
Java.Lang.Arrays

### ISSUE THREAD

**Issue by loint** [tiny-express/native#25]

**Comment by neacao** [comment]
**01/06**
> 1. Discuss about size of array C++ - solution: use Array instead
> 2. Research about dynamic array in C++ 
> 3. Define header for Arrays

**Comment by neacao** [comment]
**02/06**
> 1. Implement binarySearch and create test case follow
> 2. Implement sort and create test case follow
> 3. Discuss and make a remove virtual at Object and Number to downcast Class in C++

**Comment by neacao** [comment]
**05/06**
> 1. Research about Comparable on Oracle's document
> 2. Create comparable in Inteter, create test case
> 3. Implement some miss operator in String
> 4. Implement copyOf() and create test case follow
> 5. Implement fill() and create test case follow : not complete yet

**Comment by neacao** [comment]
**06/06**
> 1. Complete fill() and test case follow
> 2. Imeplement hashCode() follow java's source code
> 3. Research about modify data of Array<T> inside a function: pass pointer into that function
> 4. Overview current Arrays and make comment to discuss more

**Comment by neacao** [comment]
**07/06**
> 1. Remove fill(Array<boolean> original, boolean val) - use fill(Array<int> original, int val) instead
> 2. Verify comment inside Arrays
> 3. Make test cast for BOOL (a define of int)
> 4. Research type casting to deal with copyOf(Array<U> u, T newType)

**Comment by neacao** [comment]
**08/06**
> 1. Trace and fix problem with Object: should to use <T> instead
> 2. Trace and fix problem with Array<boolean>, redefine boolean = int
> 3. Research about type casting in C++ and do some sample
